// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfwqjkbpvfmvpxvzkbnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5md3Fqa2JwdmZtdnB4dnprYm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyODQ4MzIsImV4cCI6MjA3NTg2MDgzMn0.pxg1IKhTVwZgwvAoIBlarDvyAHIWU4PKjb9O7mYHfr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});